export default[
    {
        id:0,
        name:'dingdaxia',
        love:"eatting"
    },
    {
        id:1,
        name:'xiaoxiao',
        love:"playing"
    },
    {
        id:2,
        name:'jjking',
        love:"gameing"
    },
    {
        id:3,
        name:'daijj',
        love:"loving"
    },
    {
        id:4,
        name:'xionjiajun',
        love:"qiyi"
    },
    {
        id:5,
        name:'dingdaxia',
        love:"eatting"
    },
    {
        id:6,
        name:'shege',
        love:"gaming"
    },
    {
        id:7,
        name:'bo',
        love:"coding"
    },
    {
        id:8,
        name:'zhuageng',
        love:"joking"
    },
]